import { Fragment, useCallback, useEffect, useState } from 'react';
import { ArrowUpRight, ArrowRight, BookOpen, FilePlus, FlaskConical, Plus, Check, X } from 'lucide-react';
import { api, date, setCsrf, type Session } from './api';
import { Shell, SignIn, Stat, Badge, Empty, Notice } from './ui';

type Citation={chunk_id:number;document_id:string;title:string;quote:string;start_line:number;end_line:number};
type Answer={id:string;question:string;answer:string;citations:Citation[];status:string;duration_ms:number;estimated_cost:number|null;mode:string;input_tokens:number;output_tokens:number;created_at:string};
type Note={id:string;title:string;answer:string;status:string;citations:Citation[];reviewed_at:string|null};
type Eval={id:string;mode:string;passed:number;total:number;created_at:string;cases:{question:string;expected:string;answer:string;passed:boolean}[]};
type Data={documents:{id:string;title:string;chunks:number;flagged:number}[];answers:Answer[];notes:Note[];evaluations:Eval[];api_available:boolean};
type Document={id:string;title:string;passages:{id:number;passage:string;start_line:number;end_line:number;flagged:boolean}[]};

function QuoteText({text}:{text:string}){
  // Show source headings without the Markdown marks.
  return <div className="answer">{text.split(/\r?\n/).map((line,index)=>{
    const heading=line.match(/^ {0,3}#{1,6}[\t ]+(.+?)(?:[\t ]+#+)?[\t ]*$/);
    return <Fragment key={index}>{index>0?'\n':null}{heading?<strong>{heading[1]}</strong>:line}</Fragment>;
  })}</div>;
}

export default function App(){
  const [session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true);
  const [data,setData]=useState<Data|null>(null),[answer,setAnswer]=useState<Answer|null>(null),[document,setDocument]=useState<Document|null>(null);
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[tab,setTab]=useState('Ask a question');
  const [question,setQuestion]=useState(''),[mode,setMode]=useState('local'),[title,setTitle]=useState(''),[text,setText]=useState(''),[threshold,setThreshold]=useState('0.16');
  const refresh=useCallback(async()=>{setData(await api<Data>('/dashboard'));},[]);
  useEffect(()=>{api<Session>('/session').then(s=>{setSession(s);setCsrf(s.csrf);}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
  useEffect(()=>{if(session?.user)refresh().catch(e=>setError(e.message));},[session,refresh]);
  async function act(work:()=>Promise<unknown>,success:string){setBusy(true);setError('');setMessage('');try{await work();await refresh();setMessage(success);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  function source(c:Citation){act(async()=>{setDocument(await api<Document>(`/documents/${c.document_id}`));setTab('Documents');window.setTimeout(()=>window.location.hash=`passage-${c.chunk_id}`,50);},'');}
  function citations(rows:Citation[]){return rows.map((c,i)=><button className="source-link" key={`${c.chunk_id}-${i}`} onClick={()=>source(c)}><BookOpen size={14}/>{c.title}<small>Lines {c.start_line}-{c.end_line}</small><ArrowUpRight size={13}/></button>);}
  if(loading)return <div className="empty">Opening Source Notes...</div>;
  if(!session?.user)return <SignIn index={2} onLogin={setSession}/>;
  const pending=data?.notes.filter(n=>n.status==='pending')??[];
  const answered=data?.answers.filter(a=>a.status==='answered').length??0;
  return <Shell index={2} user={session.user} onLogout={()=>{api('/logout',{}).then(()=>setSession(null)).catch(e=>setError(e.message));}}><div className="content"><div className="page-heading"><div><span className="eyebrow">ANSWERS YOU CAN TRACE</span><h1>Start with the source.</h1><p>Find a passage. Read it in context. Decide what to keep.</p></div><button className="primary" disabled={busy} onClick={()=>act(()=>api('/samples',{}),'The two sample guides are ready to search.')}><Plus size={15}/>Load sample guides</button></div><Notice error={error} message={message}/>
    <div className="stats"><Stat label="Documents" value={data?.documents.length??0} note="Available in this workspace"/><Stat label="Answers with quotes" value={answered} note="From the 30 most recent questions"/><Stat label="Waiting for review" value={pending.length} note="Notes need a person's decision"/><Stat label="Answer mode" value={<span className="text-stat">{mode==='local'?'Local search':'API assisted'}</span>} note={mode==='local'?'No paid model calls':'Source quotes checked after each call'}/></div>
    <div className="tabs" role="tablist" aria-label="Source Notes sections">{['Ask a question','Documents','Review notes','Quality checks'].map(t=><button key={t} role="tab" aria-selected={tab===t} className={tab===t?'selected':''} onClick={()=>setTab(t)}>{t}{t==='Review notes'&&pending.length?` (${pending.length})`:''}</button>)}</div>
    {tab==='Ask a question'&&<div className="split"><section className="panel"><div className="panel-header"><div><h2>What would you like to find?</h2><p>Answers use exact quotes from the documents you added.</p></div></div><form onSubmit={e=>{e.preventDefault();act(async()=>setAnswer(await api<Answer>('/questions',{question,key:crypto.randomUUID(),mode})), '');}}><div className="question-box"><label style={{margin:0}}><span className="muted">Your question</span><textarea value={question} onChange={e=>setQuestion(e.target.value)} required minLength={3} maxLength={600} placeholder="Who must approve a stock adjustment?"/></label><div className="question-bottom"><span>{mode==='local'?'Matches words in your documents.':'Uses the configured model to select source quotes.'}</span><button disabled={busy||!data?.documents.length} className="primary">{busy?'Finding passages...':'Find an answer'}<ArrowRight size={14}/></button></div></div><label>Answer method<select value={mode} onChange={e=>setMode(e.target.value)}><option value="local">Local search, no API cost</option><option value="api" disabled={!data?.api_available}>API assisted{data?.api_available?'':' (not connected)'}</option></select></label></form>{answer?<article><div className="order-top"><Badge value={answer.status}/><span className="tiny" style={{margin:0}}>{answer.duration_ms} ms · {answer.mode} · {answer.estimated_cost===null?'Cost not configured':`$${Number(answer.estimated_cost).toFixed(6)}`}</span></div><QuoteText text={answer.answer}/>{citations(answer.citations)}{answer.status==='answered'&&<button className="secondary" style={{marginTop:20}} disabled={busy} onClick={()=>act(()=>api('/notes',{answer_id:answer.id,title:answer.question.slice(0,120)}),'Note sent to the review list. It is not approved yet.')}><FilePlus size={15}/>Send note for review</button>}</article>:<Empty title={data?.documents.length?'Your answer will appear here':'Add the sample guides to begin'}>A question with no matching passage will receive no answer. You can always open a source and read it yourself.</Empty>}</section>
      <aside><section className="panel"><h2>Try a question</h2><p className="muted">These use the two sample guides.</p>{['Who must approve a stock adjustment?','Where should damaged boxes go?','What is the morning delivery window?','How much is the employee dental insurance premium?'].map(q=><button key={q} className="question-preset" onClick={()=>setQuestion(q)}>{q}</button>)}<div className="subtle-box"><p>The last question has no answer in the sample documents. The app should say so.</p></div></section><section className="panel"><h2>Recent questions</h2>{!data?.answers.length?<p className="muted">No questions yet.</p>:data.answers.slice(0,6).map(a=><div className="activity" key={a.id}><div><button className="text-button" onClick={()=>setAnswer(a)}>{a.question}</button><small>{date(a.created_at)} · {a.status}</small></div></div>)}</section></aside></div>}
    {tab==='Documents'&&<div className="split"><div><section className="panel"><div className="panel-header"><div><h2>Your source library</h2><p>Plain text and Markdown, split into passages with line numbers.</p></div></div>{!data?.documents.length?<Empty title="The library is empty"/>:data.documents.map(d=><div className="document-row" key={d.id}><span className="document-icon"><BookOpen size={20}/></span><div><strong>{d.title}</strong><small>{d.chunks} passages · {d.flagged} excluded from search</small></div><button className="small" onClick={()=>act(async()=>setDocument(await api<Document>(`/documents/${d.id}`)),'')}>Read<ArrowUpRight size={13}/></button></div>)}</section>{document&&<section className="panel"><div className="panel-header"><h2>{document.title}</h2><button className="small" onClick={()=>setDocument(null)}>Close</button></div>{document.passages.map(p=><div id={`passage-${p.id}`} className={'passage '+(p.flagged?'flagged':'')} key={p.id}><span className="eyebrow">LINES {p.start_line}-{p.end_line}{p.flagged?' · EXCLUDED FROM SEARCH':''}</span>{p.passage}</div>)}</section>}</div><form className="panel" onSubmit={e=>{e.preventDefault();act(async()=>{await api('/documents',{title,text});setTitle('');setText('');},'Document added to the library.');}}><h2>Add a document</h2><p className="muted">Use sample business notes or a guide you have permission to use.</p><label>Text or Markdown file<input type="file" accept=".txt,.md,text/plain,text/markdown" onChange={e=>{const file=e.target.files?.[0];if(file){act(async()=>{if(file.size>100000)throw new Error('Choose a file smaller than 100 KB.');setTitle(file.name);setText(await file.text());},'File loaded. Review it, then add the document.');}}}/></label><label>Title<input maxLength={120} value={title} onChange={e=>setTitle(e.target.value)} required/></label><label>Document text<textarea rows={8} minLength={20} maxLength={100000} value={text} onChange={e=>setText(e.target.value)} required/></label><button className="primary" disabled={busy}><Plus size={14}/>Add document</button><p className="tiny">Passages that contain common attempts to change the app's instructions are kept for review but excluded from search. This check cannot catch every possible attempt.</p></form></div>}
    {tab==='Review notes'&&<section className="panel"><div className="panel-header"><div><h2>A person makes the last call.</h2><p>Check the quotes and their context before approving a note.</p></div></div>{!data?.notes.length?<Empty title="No notes waiting">Find an answer and send it for review.</Empty>:data.notes.map(note=><article className="order-card" key={note.id}><div className="order-top"><h3>{note.title}</h3><Badge value={note.status}/></div><QuoteText text={note.answer}/>{citations(note.citations)}{note.status==='pending'?<div className="buttons" style={{marginTop:16}}><button className="primary small" disabled={busy} onClick={()=>act(()=>api(`/notes/${note.id}/review`,{approve:true}),'Note approved.')}><Check size={14}/>Approve note</button><button className="small" disabled={busy} onClick={()=>act(()=>api(`/notes/${note.id}/review`,{approve:false}),'Note rejected.')}><X size={14}/>Reject</button></div>:<p className="tiny">Reviewed {date(note.reviewed_at)}</p>}</article>)}</section>}
    {tab==='Quality checks'&&<div className="split"><div><section className="panel"><div className="panel-header"><div><h2>Check the same questions again</h2><p>Eight fixed questions test sample answers and missing information.</p></div></div>{!data?.evaluations.length?<Empty title="Run the first check">Load the sample guides, then run the questions. Try a different match threshold to compare the results.</Empty>:data.evaluations.map(run=><article className="order-card" key={run.id}><div className="order-top"><h3>{run.passed} / {run.total} passed</h3><Badge value={run.passed===run.total?'completed':'warnings'}/></div><p>{run.mode} · {date(run.created_at)}</p>{run.cases.map(c=><div className="eval-case" key={c.question}><Badge value={c.passed?'completed':'failed'}/><strong>{c.question}</strong><p>Expected: {c.expected}</p><p>{c.answer}</p></div>)}</article>)}</section><section className="panel"><h2>Request log</h2><div className="table-wrap"><table><thead><tr><th>Question</th><th>Result</th><th>Time</th><th>Tokens in / out</th><th>Est. cost</th></tr></thead><tbody>{data?.answers.map(a=><tr key={a.id}><td>{a.question}</td><td><Badge value={a.status}/></td><td>{a.duration_ms} ms</td><td>{a.input_tokens} / {a.output_tokens}</td><td>{a.estimated_cost===null?'Unknown':`$${Number(a.estimated_cost).toFixed(6)}`}</td></tr>)}</tbody></table></div></section></div><form className="panel" onSubmit={e=>{e.preventDefault();act(()=>api('/evaluations',{threshold:Number(threshold)}),'Quality check saved.');}}><FlaskConical size={26} style={{marginBottom:15,color:'var(--accent)'}}/><h2>Run a local check</h2><p className="muted">This measures local search only. A live model needs a separate evaluation after its API is connected.</p><label>Minimum match score<input type="number" step="0.01" min="0.05" max="0.8" value={threshold} onChange={e=>setThreshold(e.target.value)} required/></label><button className="primary" disabled={busy||!data?.documents.length}>Run eight questions</button><div className="subtle-box"><p>A higher score asks for a closer word match. It may miss useful passages. A lower score can return passages that do not answer the question.</p></div></form></div>}
  </div></Shell>;
}
